[MS-1229] fix rendered hooks issue
error: Rendered more hooks than during the previous render
solution: move if (!reviews) below useMediaQuery hook

- also go back to if(isMobile) instead of ternary op
for better readability